web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - .:/code
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
    image: php:7-fpm
    volumes: 
        - .:/code
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal