version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - "/docker/wordpress/mysql:/var/lib/mysql"
    restart: unless-stopped
    container_name: "wordpress_db"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress     
  wordpress:
    image: wordpress:latest
    ports:
     - "8888:80"      
    volumes:
      - "/docker/wordpress/html:/var/www/html"
    depends_on:
      - "db"      
    restart: unless-stopped
    container_name: "wordpress"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  adminer:
    container_name: "wordpress_adminer"  
    image: adminer:standalone
    restart: unless-stopped   
    ports:
     - "9001:8080"     
    depends_on:
      - db
